### ISSUE TITLE
Figure out the right name for SingleElement*

### ISSUE THREAD

**Issue by jsbean** [jsbean/XMLCoder#31]
We currently have a handful of types which are called `SingleElement*` (`SingleElementBox`, etc.). The purpose of these types is to represent the ambiguity between elements in an unkeyed container which could be nested unkeyed container elements or choice elements.

We can't quite know a type is going to be a choice type until a certain point through the process, and until then we have to hold onto the ambiguity in some structured way.

I don't think that `SingleElement*` is the right bucket of words, but don't have an intuition yet regarding a better one.

@bwetherfield, any ideas?

**Comment by bwetherfield** [comment]
`LabeledBox`, `MediatorBox`, `WrappedBox`, or just `ElementBox`?

**Comment by bwetherfield** [comment]
Yeah I actually kind of like `ElementBox`. @jsbean ?

**Comment by bwetherfield** [comment]
I envisage this making sense as a way of phasing out the use of the `value` intrinsic too

**Comment by jsbean** [comment]
Works for me. It’s just a way of saying: don’t throw away anything when descending into this element, we will deal with it down there.

**Comment by jsbean** [comment]
Does this still feel good in the context of `XMLElementEncoder`?

**Comment by bwetherfield** [comment]
I guess the complication is that we won't use it this way for _every_ element. At least for the timebeing

**Comment by jsbean** [comment]
Right, it’s just for a very specific subset of elements which are ambiguous at the point of initial XML parsing and XMLCoderElement initialization.

**Comment by jsbean** [comment]
What about `KeyedElementBox` ? Or `SingleKeyedElementBox` ?

**Comment by jsbean** [comment]
Or `SingleKeyedBox` 🙃

**Comment by jsbean** [comment]
I'm gonna close this for now. If we don't like it, we can reopen. It's all internal anyway.
